import {
  GIF_FILE,
  JPEG_FILE,
  JPG_FILE,
  MICROSOFT_EXCEL_WORKBOOK_FILE,
  MICROSOFT_POWERPOINT_PRESENTATION_FILE,
  MICROSOFT_WORD_DOCUMENT_FILE,
  PDF_DOCUMENT_FILE,
  PNG_FILE,
} from "./filesExtensions";

import {
  DEFAULT_FILE_ICON,
  GIF_FILE_ICON,
  IMAGE_FILE_ICON,
  JPG_FILE_ICON,
  MICROSOFT_EXCEL_WORKBOOK_FILE_ICON,
  MICROSOFT_POWERPOINT_PRESENTATION_FILE_ICON,
  MICROSOFT_WORD_DOCUMENT_FILE_ICON,
  PDF_DOCUMENT_FILE_ICON,
  PNG_FILE_ICON,
} from "./filesIcons";

export {
  GIF_FILE,
  JPEG_FILE,
  JPG_FILE,
  MICROSOFT_EXCEL_WORKBOOK_FILE,
  MICROSOFT_POWERPOINT_PRESENTATION_FILE,
  MICROSOFT_WORD_DOCUMENT_FILE,
  PDF_DOCUMENT_FILE,
  PNG_FILE,
  DEFAULT_FILE_ICON,
  GIF_FILE_ICON,
  IMAGE_FILE_ICON,
  JPG_FILE_ICON,
  MICROSOFT_EXCEL_WORKBOOK_FILE_ICON,
  MICROSOFT_POWERPOINT_PRESENTATION_FILE_ICON,
  MICROSOFT_WORD_DOCUMENT_FILE_ICON,
  PDF_DOCUMENT_FILE_ICON,
  PNG_FILE_ICON,
};
