import {
  MICROSOFT_WORD_DOCUMENT_FILE,
  MICROSOFT_POWERPOINT_PRESENTATION_FILE,
  MICROSOFT_EXCEL_WORKBOOK_FILE,
  GIF_FILE,
  JPG_FILE,
  JPEG_FILE,
  PNG_FILE,
  PDF_DOCUMENT_FILE,
  MICROSOFT_WORD_DOCUMENT_FILE_ICON,
  MICROSOFT_POWERPOINT_PRESENTATION_FILE_ICON,
  MICROSOFT_EXCEL_WORKBOOK_FILE_ICON,
  GIF_FILE_ICON,
  JPG_FILE_ICON,
  PNG_FILE_ICON,
  PDF_DOCUMENT_FILE_ICON,
  IMAGE_FILE_ICON,
  DEFAULT_FILE_ICON,
} from "../constants";

const fileIconByExtension = {
  [MICROSOFT_WORD_DOCUMENT_FILE]: MICROSOFT_WORD_DOCUMENT_FILE_ICON,
  [MICROSOFT_POWERPOINT_PRESENTATION_FILE]: MICROSOFT_POWERPOINT_PRESENTATION_FILE_ICON,
  [MICROSOFT_EXCEL_WORKBOOK_FILE]: MICROSOFT_EXCEL_WORKBOOK_FILE_ICON,
  [GIF_FILE]: GIF_FILE_ICON,
  [JPG_FILE]: JPG_FILE_ICON,
  [JPEG_FILE]: IMAGE_FILE_ICON,
  [PNG_FILE]: PNG_FILE_ICON,
  [PDF_DOCUMENT_FILE]: PDF_DOCUMENT_FILE_ICON,
};

export const getFileIconByExtension = (fileExtension) => {
  return fileIconByExtension[fileExtension] || DEFAULT_FILE_ICON;
}
